[package]
name = "onlyone"
version = "1.0.0"
authors = ["flux"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2"
regex = "1"

